[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Handcalcs = "e8a07092-c156-4455-ab8e-ed8bc81edefb"
HyperdimensionalComputing = "ebb7690e-f605-4e7a-86a0-727dbed6b293"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
